set runtimepath+=~/dotfiles/vim/

source ~/dotfiles/lib/vim/base/vimrcs/basic.vim
" source ~/dotfiles/lib/vim/base/vimrcs/filetypes.vim
" source ~/dotfiles/lib/vim/base/vimrcs/plugins_config.vim
" source ~/dotfiles/lib/vim/base/vimrcs/extended.vim

try
source ~/dotfiles/var/local.vim
catch
endtry
